[cursor]
style.blinking = "Always"
style.shape = "Underline"

[env]
TERM = "xterm-256color"

[font]
size = 14
bold.style = "SemiBold"
normal.family = "ComicShannsMono Nerd Font Mono"
normal.style = "Regular"

[scrolling]
history = 100000
multiplier = 3

[selection]
save_to_clipboard = true

[terminal]
shell.program = "/run/current-system/sw/bin/nu"

[window]
opacity = 0.6
padding.x = 24
padding.y = 16

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "SearchForward"
key = "F"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "SearchBackward"
key = "B"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
key = "O"
mods = "Control|Shift"
action = "SpawnNewInstance"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "Space"
mods = "Control|Shift"

[[keyboard.bindings]]
key = "H"
mods = "Alt"
chars = "\u001bOH"

[[keyboard.bindings]]
key = "J"
mods = "Alt"
chars = "\u001bOJ"

[[keyboard.bindings]]
key = "K"
mods = "Alt"
chars = "\u001bOK"

[[keyboard.bindings]]
key = "L"
mods = "Alt"
chars = "\u001bOL"
